services:
  - type: web
    name: song-raptor-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        value: AIzaSyCWCn6ulx-vRDyHDThaHMxUQfdOWN2GNM0

  - type: web
    name: song-raptor-frontend
    env: static
    plan: free
    buildCommand: echo "No build needed for static files"
    staticPublishPath: ./frontend